### ISSUE TITLE
log(p) = -Inf

### ISSUE THREAD

**Issue by hyaochn** [majkamichal/naivebayes#2]
In predict.naive_bayes, around line 46 and 50, p might be =0
p[p==0]=threshold should be added to get -Inf for log(p).

**Comment by majkamichal** [comment]
For discrete features, you can use Laplace smoothing to avoid zero probabilities. Therefore there is no need to include `p[p==0] <- threshold` around lines 46-50.  This method is not applicable to continuous features and hence there is `p[p==0] <- threshold` around lines 20-38.

Thank you for the interest in the code!
