### ISSUE TITLE
Error when feeding just 1 predictor into Naivebayes model

### ISSUE THREAD

**Issue by BharatAD** [majkamichal/naivebayes#3]
```
>     i<-2
>     nbmodel<-naive_bayes(data=trainset, y=trainset$label,x=trainset[2:i],usekernel= TRUE)
>     nbmodel_predict<-predict(nbmodel,as.vector(x_test))
Warning message:
In t(log_sum) + log(prior) :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.
```

I suppose the package does not expect to handle a data-set with just 1 feature? Or i am misunderstanding some fundamental concept here.

**Comment by jamesfrj** [comment]
Did you fix it?

**Comment by majkamichal** [comment]
Hello,

First of all, I am sorry for such late response. I could state many reasons for that but that is not relevant at all. That should not have happened.

The problem with the code above is that you pass a `vector` to the `predict.naive_bayes` function. Just like it is stated in the `?predict.naive_bayes`, the function expects a `matrix` or a `data.frame` as `newdata`. The names of columns in the `newdata` are then matched to the names of tables stored in the `object`:

`View(naivebayes:::predict_naivebayes)`
Line 15: ` features <- names(newdata)[names(newdata) %in% names(tables)]`.

Your example makes it clear that I should improve the error handling and add an informative error that requests changing a vector into a matrix/data.frame in the updated version of the code.

Best regards,
Michał
