### ISSUE TITLE
Extracting feature importance

### ISSUE THREAD

**Issue by kohlkopf** [majkamichal/naivebayes#8]
Excellent package! The most accessible approach to NB classification that I've found.

I'm wondering if there is a way to extract feature weight/importance from the model? I didn't see any relevant accessors nor any obvious slots in the `naive_bayes` object.

**Comment by majkamichal** [comment]
Hi! Thank you for your compliment! Currently naivebayes doesn't offer such functionality. Do you have any suggestion how would it work within the Naive Bayes framework?

**Comment by majkamichal** [comment]
Hi!
One way of extracting feature importance is to use the `Caret` package. You can find more information here:
- https://topepo.github.io/caret/variable-importance.html
- https://stackoverflow.com/questions/62849037/determine-variables-of-importance-in-naive-bayes-model/62884652#62884652

Best,
Michal
