### ISSUE TITLE
How to use additional density()-parameters for naive_bayes() tuning

### ISSUE THREAD

**Issue by AndreM84** [majkamichal/naivebayes#9]
I was wondering, if further additional parameters of the `stats::density()` function can be used when executing `naive_bayes()`.

Actually, I am applying the naive_bayes() classifier on a mixed variables data set where most of the numeric data is non-negative. For this reason a log-normal prior-distribution or a KDE, which ensures no probabilities for values < 0 are estimated, seem to be a good choice for my case.
The `stats::density()` function, which you used for the KDE in `naive_bayes()` has the argument **'to'**, which could ensure probablities for values < 0 are zero.

Is it possible to make use of this argument when executing the `naive_bayes()` with `kernel= TRUE`?

Many thanks in advance for any reply and best regards
André

**Comment by majkamichal** [comment]
Hi André,

you can use all `stats:density()` parameters in `naive_bayes()` by passing them via `...` functionality. It is all well documented.

**Example:**

```
library(naivebayes)
# Simulate example data
n <- 100
set.seed(1)
data <- data.frame(class = sample(c("classA", "classB"), n, TRUE),
                   norm = rnorm(n),
                   count = rpois(n, lambda = c(5,15)))
train <- data[1:95, ]
test <- data[96:100, -1]

summary(data$norm)

nb <- naive_bayes(class ~ norm, train, usekernel = TRUE)
plot(nb)

nb2 <- naive_bayes(class ~ norm, train, usekernel = TRUE, from = 0, to = 5)
plot(nb2)
```

Best,
Michal

**Comment by AndreM84** [comment]
Thank you for your response and the clarification!
For whatever reason I missed the `...`  explanations in the docs of your package. Sorry for that.
